openapi: 3.0.0
info:
  title: Catalog API
  version: 1.0.0
paths:
  /api/catalog/{id}/prizes:
    get:
      summary: Retrieve prizes for a catalog
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the catalog
        - name: id
          in: query
          required: false
          schema:
            type: integer
          description: The ID of the prize
        - name: description
          in: query
          required: false
          schema:
            type: string
          description: The description of the prize
        - name: page
          in: query
          required: false
          schema:
            type: integer
          description: The page number for pagination, must be used together with per_page
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
          description: The number of items per page for pagination, , must be used together with page
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    example: 10
                  prizes:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: "Prize 1"
                        description:
                          type: string
                          example: "Description of prize 1"
                        image:
                          type: string
                          example: "https://example.com/image1.png"
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
                example: "Bad Request"
        '500':
          description: Internal server error
          content: {}
      x-codegen-request-body-name: body
